# Generated by Django 3.0.8 on 2020-08-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='School')),
                ('maximum_students_count', models.PositiveSmallIntegerField(verbose_name='Maximum of students')),
            ],
        ),
    ]
